# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/v2a-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter chagalllte chagallwifi klimtlte klimtltecan klimtwifi n1awifi n2awifi v1awifi v2awifi,$(TARGET_DEVICE)),)

endif
